#!bin/bash
cd
cp -r /scratch/user/mall0133/PHAGE_BUBBLE #username
cd ~/minimap2/
# This step will generate the DNA files: the genome of the variants and the reference named Path 1 and Path 2.

# Alignment: 
while read line;
do
    echo $line
    for i in {1..2}
    do
        ./minimap2 -ax sr -t 32 ~/PHAGE_BUBBLE/path_$i.fasta ~/PHAGE_BUBBLE/reads/$line"_R1_001.fastq.gz" ~/PHAGE_BUBBLE/reads/$line"_R2_001.fastq.gz" > ~/PHAGE_BUBBLE/$line"_path_"$i".sam"
        
        samtools view -b -S -@ 32 ~/PHAGE_BUBBLE/$line"_path_"$i".sam" > ~/PHAGE_BUBBLE/Bam/$line"_path_"$i".bam"
        samtools sort -@ 32 ~/PHAGE_BUBBLE/Bam/$line"_path_"$i".bam" -o ~/PHAGE_BUBBLE/Bam_sorted/$line"_path_"$i"_sorted.bam"
        samtools index -@ 32 ~/PHAGE_BUBBLE/Bam_sorted/$line"_path_"$i"_sorted.bam"
    done
done < /home/pham0323/name_file.txt
